/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import java.io.IOException;
import java.io.File;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;

public class App {
    public static void main(String[] args) throws IOException {
        if(args.length < 3) {
            System.out.println("Usage: ./gradlew run --args InputPath OutputPath TransformOperation");
            System.exit(1);
        }
        File inputFile = new File(args[0]);
        File outputFile = new File(args[1]);
        String transformName = args[2];

        BufferedImage inputImage = new ImageIO.read(inputFile);
            Bitmap bitmap = new Bitmap(inputImage);

            if (transformName.equals("greyscale")) {
                bitmap.greyscale();
            } else {
                System.out.println("Transform Not a Method");
                System.exit(1);
            }
            ImageIO.write(bitmap.toBufferedImage(), "bmp", outputFile);
    }
}

    C:\Users\Davey's PCSDocuments\CODE_FELLOWS\401java\code-401\labs\Apps\bitmap-transformer\app\src\main\resources\baldy-8bit.bmp